name: Scala CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - uses: coursier/cache-action@v5
      - uses: AvaPL/scalafmt-native-formatter@v0.1.0
      - run: csbt ^test ^scripted
      - run: csbt ^publish release
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
        env:
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ARTIFACTORY_PASS: ${{ secrets.ARTIFACTORY_PASS }}
